[tool.poetry]
name = "coursera-courses-eda"
version = "0.1.0"
description = ""
authors = ["Vytautas BuneviÄius"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
